name: Build and Package Extension

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check

      - name: Build extension
        run: npm run build

      - name: Create zip package
        run: |
          cd dist
          zip -r ../fact-it-${{ github.event.release.tag_name }}.zip .
          cd ..

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fact-it-${{ github.event.release.tag_name }}.zip
          asset_name: fact-it-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
